export interface UrlItem {
  id: string;
  shortUrl: string;
  originalUrl: string;
  description?: string;
  createdAt: string;
  clickCount: number;
}

export const dummyUrls: UrlItem[] = [
  {
    id: "1",
    shortUrl: "lill.ing/abc123",
    originalUrl: "https://www.google.com/search?q=url+shortener",
    description: "Google search for URL shorteners",
    createdAt: "2025-01-07T10:30:00Z",
    clickCount: 42,
  },
  {
    id: "2",
    shortUrl: "lill.ing/xyz789",
    originalUrl: "https://github.com/vercel/next.js",
    description: "Next.js GitHub repository",
    createdAt: "2025-01-06T15:20:00Z",
    clickCount: 128,
  },
  {
    id: "3",
    shortUrl: "lill.ing/test99",
    originalUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    createdAt: "2025-01-06T08:15:00Z",
    clickCount: 999,
  },
  {
    id: "4",
    shortUrl: "lill.ing/dev2025",
    originalUrl: "https://stackoverflow.com/questions/tagged/typescript",
    description: "TypeScript questions on Stack Overflow",
    createdAt: "2025-01-05T12:45:00Z",
    clickCount: 67,
  },
  {
    id: "5",
    shortUrl: "lill.ing/docs42",
    originalUrl: "https://react.dev/learn",
    description: "React documentation - learning path",
    createdAt: "2025-01-05T09:12:00Z",
    clickCount: 234,
  },
  {
    id: "6",
    shortUrl: "lill.ing/news01",
    originalUrl: "https://news.ycombinator.com/",
    createdAt: "2025-01-04T16:30:00Z",
    clickCount: 89,
  },
  {
    id: "7",
    shortUrl: "lill.ing/tailwind",
    originalUrl: "https://tailwindcss.com/docs",
    description: "Tailwind CSS documentation",
    createdAt: "2025-01-04T11:22:00Z",
    clickCount: 156,
  },
  {
    id: "8",
    shortUrl: "lill.ing/mdnweb",
    originalUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    createdAt: "2025-01-03T14:05:00Z",
    clickCount: 312,
  },
  {
    id: "9",
    shortUrl: "lill.ing/notion",
    originalUrl: "https://www.notion.so/product",
    description: "Notion product page for team collaboration",
    createdAt: "2025-01-03T10:40:00Z",
    clickCount: 45,
  },
  {
    id: "10",
    shortUrl: "lill.ing/figma99",
    originalUrl: "https://www.figma.com/design",
    createdAt: "2025-01-02T17:55:00Z",
    clickCount: 78,
  },
  {
    id: "11",
    shortUrl: "lill.ing/vercel",
    originalUrl: "https://vercel.com/docs",
    description: "Vercel deployment documentation",
    createdAt: "2025-01-02T13:20:00Z",
    clickCount: 201,
  },
  {
    id: "12",
    shortUrl: "lill.ing/supabase",
    originalUrl: "https://supabase.com/docs",
    createdAt: "2025-01-01T19:10:00Z",
    clickCount: 167,
  },
  {
    id: "13",
    shortUrl: "lill.ing/stripe",
    originalUrl: "https://stripe.com/docs/api",
    description: "Stripe API reference for payment integration",
    createdAt: "2024-12-31T16:45:00Z",
    clickCount: 523,
  },
  {
    id: "14",
    shortUrl: "lill.ing/local123",
    originalUrl: "http://localhost:3000/test",
    description: "Local development test page",
    createdAt: "2024-12-30T14:30:00Z",
    clickCount: 12,
  },
  {
    id: "15",
    shortUrl: "lill.ing/blog88",
    originalUrl: "https://medium.com/@author/article-title",
    createdAt: "2024-12-29T11:15:00Z",
    clickCount: 95,
  },
  {
    id: "16",
    shortUrl: "lill.ing/tweet",
    originalUrl: "https://twitter.com/username/status/123456789",
    description: "Important tweet about web development",
    createdAt: "2024-12-28T20:00:00Z",
    clickCount: 1243,
  },
  {
    id: "17",
    shortUrl: "lill.ing/reddit",
    originalUrl: "https://www.reddit.com/r/webdev/comments/example",
    createdAt: "2024-12-27T09:45:00Z",
    clickCount: 334,
  },
  {
    id: "18",
    shortUrl: "lill.ing/aws",
    originalUrl: "https://aws.amazon.com/documentation/",
    description: "AWS documentation hub",
    createdAt: "2024-12-26T15:30:00Z",
    clickCount: 456,
  },
  {
    id: "19",
    shortUrl: "lill.ing/unknown",
    originalUrl: "https://random-unknown-site-123456.com/page",
    description: "Some random site without favicon",
    createdAt: "2024-12-25T12:00:00Z",
    clickCount: 7,
  },
  {
    id: "20",
    shortUrl: "lill.ing/oldsite",
    originalUrl: "http://old-website-no-favicon.net/",
    createdAt: "2024-12-24T08:20:00Z",
    clickCount: 3,
  },
];
